#! /usr/bin/rake
#
# Rake file for building binaries, libraries and unit tests. 
#
# Examples:
#
#   rake                 # default build and test
#   rake -T              # list all defined rake tasks
#   rake clean
#   rake build          
#   rake run
#   rake test
#   rake DEBUG=TRUE target
#   etc. etc. (see rake -T).

require 'rake/clean'

array_dfiles = Dir.glob("./src/ctl/core/array/*.d")
stats_dfiles = Dir.glob("./src/ctl/core/stats/*.d")
input_dfiles = Dir.glob("./src/ctl/io/*.d") + Dir.glob("./src/ctl/io/csv/*.d")+ Dir.glob("./src/ctl/io/cmdline/*.d")
ctl_dfiles = Dir.glob("./src/ctl/core/ctl/*.d")

#Unix files
CLEAN.include('*.lib','*.o','*.dep','*.deps')
#Win32 files
CLEAN.include('*.lib','*.obj','*.exe','*.map')

TESTS = [ :mapctl ]

task "array" => array_dfiles do
  sh "dmd -lib -O -ofarray.lib #{array_dfiles.join(' ')}"
end

task "stats" => stats_dfiles do
  sh "dmd -lib -O -ofstats.lib #{stats_dfiles.join(' ')} -Isrc/"
end

task "input" => input_dfiles do
  sh "dmd -lib -O -ofinput.lib #{input_dfiles.join(' ')} -Isrc/"
end

task "ctl" => ctl_dfiles do
  sh "dmd -lib -O -ofctl.lib #{ctl_dfiles.join(' ')} -Isrc/"
end

file "mapctl" => ["ctl","input","stats","array"] do
  sh "dmd -O src/ctl/mapctl.d array.lib stats.lib input.lib ctl.lib -Isrc/"
end



desc "Default build and tests"
task :default => [:build]

desc "Build default binaries"
task :build => TESTS



