#! /usr/bin/rake
#
# Rake file for building binaries, libraries and unit tests. 
#
# Examples:
#
#   rake                 # default build and test
#   rake -T              # list all defined rake tasks
#   rake clean           # clean
#   rake qtab            # custom target
#   etc. etc. (see rake -T).

require 'rake/clean'

def windows?; return RUBY_PLATFORM =~ /(:?mswin|mingw)/ ; end

qtlhd="../../qtlHD/src/D"

if ENV['QTLHD']==nil and not File.directory?(qtlhd)
  puts "Compiling without qtab support!"
  puts ""
  puts "Check out the qtlHD directory, or"
  puts "set the QTLHD environment variable to enable qtab format"
  puts " -e.g. set QTLHD=c:/github/qtlHD/src/D"
  puts ""
  hasQTAB = false
else
  puts "Compiling with qtab support!"
  qtlhd = ENV['QTLHD'] if ENV['QTLHD']
  hasQTAB = true
end
  
LIB_PREFIX = if(windows?) then '' else 'lib' end
if(windows?) then LIB_EXT = 'lib' ; else LIB_EXT = 'a' ; end

input_lib_arg = ""
compile_args  = "-O -w -inline"
stats_lib_arg = ""
mapctl_deps = ["qtllib","ctl","input","stats","array"]
used_libs = []

array_dfiles = Dir.glob("./src/ctl/core/array/*.d")
stats_dfiles = Dir.glob("./src/ctl/core/*.d") + Dir.glob("./src/ctl/core/stats/*.d")
qtl_dfiles = Dir.glob("./src/ctl/core/qtl/*.d")
input_dfiles = Dir.glob("./src/ctl/io/*.d") + Dir.glob("./src/ctl/io/csv/*.d")+ Dir.glob("./src/ctl/io/cmdline/*.d")
ctl_dfiles = Dir.glob("./src/ctl/core/ctl/*.d")
qtab_dfiles = []

if hasQTAB
  qtab_dfiles  = Dir.glob(qtlhd + "/qtl/core/*.d") + ["#{qtlhd}/qtl/plugins/qtab/read_qtab.d"] + ["src/ctl/io/qtab/wrapper.d"]
  compile_args += " -I#{qtlhd} -version=QTAB"
  mapctl_deps += "qtab.#{LIB_EXT}"
end

if windows?
  CLEAN.include("*.#{LIB_EXT}","qtls.txt","lods*.txt","perms*.txt","ctl*.txt","",'./test/output/*.txt','*.obj','*.exe','*.map','mapctl.exe')
else
  CLEAN.include('*.a','*.o',"qtls.txt","lods*.txt","perms*.txt","ctl*.txt",'*.dep','*.deps','mapctl')
end

TESTS = [ :mapctl ]

directory "test/output"

file "array" => array_dfiles do
  sh "dmd -lib #{compile_args} -ofarray.#{LIB_EXT} #{array_dfiles.join(' ')}"
end

file "stats" => stats_dfiles do
  sh "dmd -lib #{compile_args} -ofstats.#{LIB_EXT} #{stats_dfiles.join(' ')} -Isrc/"
end

task "input" => input_dfiles do
  sh "dmd -lib #{compile_args} -ofinput.#{LIB_EXT} #{input_dfiles.join(' ')} #{input_lib_arg} -Isrc/"
  used_libs += ["input.#{LIB_EXT}"]
end

task "ctl" => ctl_dfiles do
  sh "dmd -lib #{compile_args} -ofctl.#{LIB_EXT} #{ctl_dfiles.join(' ')} -Isrc/"
  used_libs += ["ctl.#{LIB_EXT}"]
end

task "qtllib" => qtl_dfiles do
  sh "dmd -lib #{compile_args} -ofqtl.#{LIB_EXT} #{qtl_dfiles.join(' ')} -Isrc/"
  compile_args += " -version=QTL"
  used_libs += ["qtl.#{LIB_EXT}"]
end

file "qtab.#{LIB_EXT}" => qtab_dfiles do
  sh "dmd -lib #{compile_args} -ofqtab.#{LIB_EXT} #{qtab_dfiles.join(' ')} -Isrc/"
  used_libs += ["qtab.#{LIB_EXT}"]
end

file "mapctl" => mapctl_deps do
  sh "dmd #{compile_args} src/ctl/mapctl.d #{used_libs.join(' ')} stats.#{LIB_EXT} array.#{LIB_EXT} -Isrc/"
end

desc "Test mapctl"
task :test_all => [ "test/output", :mapctl ] do 
  print "Testing mapctl\n"
  sh "./mapctl --help"
  sh "./mapctl -h -v"
  sh "./mapctl --nperms=5 -o=test/output/hyper"
end

desc "Default build and tests"
task :default => [:build, :test]

desc "Build mapctl"
task :build => [:mapctl]

desc "Build mapctl with qtab support"
task :qtab => ["qtab.#{LIB_EXT}","mapctl"] 

desc "Test mapqtl with qtab support"
task :test_qtab => [ "test/output/multi", :qtab ]  do
  sh "./mapctl --help"
  sh "./mapctl --format=qtab  -p=test/data/multi_phenotypes.qtab -g=test/data/multi --overwrite -o=test/output/multi"
end

